# Generated by Django 2.2.7 on 2020-01-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_friend',
            new_name='Friends',
        ),
    ]
